factory_method_#1
Cxrdary/PIRGBControl pull request #1
Opened 2023-10-01 06:39 UTC by MichaelAndrew22

_Basic Implementation and demonstration of the factory method pattern._
Prototype #1 (can easily be improved)

 To design the led_strip classes we need to locate led_strip methods, (which I can't locate in diozero), eyes needed on locating led_strip methods in order to make these strip classes that the factory then instantiates based on string input.

Also, this is the new repo we are working from right? If so can we get the issues going on this bad boy?
Thanks for all your help :)

2023-10-01 06:41 UTC, MichaelAndrew22 commented on pidev/src/main/java/models/Device.java
> -    private String deviceName;
Might want to keep these private? 
Is there a way to merge everything but this?

2023-10-01 06:43 UTC, MichaelAndrew22 commented on pidev/src/main/java/led/lightstrip/scrum5/pidev/PidevApplication.java
> +		Device myDevice = new factory().createDevice("neopixel");
Can change this to use parameter passed into factory. In the constructor createDevice() can happen.

2023-10-01 06:43 UTC, MichaelAndrew22 reviewed
Some things can be polished but I think this is a pretty basic framework of the factory method in action.

2023-10-02 21:10 UTC, Cxrdary requested changes
looks good, merge into the dev branch please

2023-10-03 06:39 UTC, MichaelAndrew22 commented
Check this out, I think this is ultimately what he's going to teach us and then we are going to adopt it.

https://pi4j.com/getting-started/javafx-mvc-template/

2023-10-03 06:39 UTC, closed without merging